[package]
name = "snowpipe-streaming"
version = "0.1.0"
edition = "2024"
publish = ["shared-package-domain-cargo-store"]

[dependencies]
jiff = "0.2.15"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.143"
